### ISSUE TITLE
Fails at Part 2 OF 4 - Not finding/creating boundary layers

### ISSUE THREAD

**Issue by jakc** [minus34/gnaf-loader#13]
Postgres 9.5.3, PostGIS 2.2.2 
Anaconda 2.4.1 (32-bit) - Python 2.7.12
psycopg2-win-py27 - 2.6.1
All installed on a Windows 10 local machine.

Created an empty database in postgres called _gnaf_May16_
![1](https://cloud.githubusercontent.com/assets/2769383/16676840/82140764-4512-11e6-9345-f4ae0b115135.png)

Have downloaded the May 2016 GNAF and the Admin boundaries
![paths](https://cloud.githubusercontent.com/assets/2769383/16676775/8986b2cc-4511-11e6-9fae-d591aaf4729c.gif)

Only modifications made to load-gnaf.py are to hard-code in my PGDATABASE, PGUSER, PGPASSWORD details.

Running load-gnaf.py with the following parameters:
`python load-gnaf.py --gnaf-tables-path="D:\DemoFolder\G-NAF\Downloads\MAY16_GNAF_PipeSeparatedValue_20160523140820\G-NAF\G-NAF MAY 2016" --admin-bdys-path="D:\DemoFolder\G-NAF\Downloads" --states TAS ACT`

Fails at Part 2 OF 4.
```
relation "raw_admin_bdys.aus_state" does NOT exist
LINE 12:   FROM raw_admin_bdys.aus_state AS tab
```
[Full log here.](http://pastebin.com/tGrH9J8d)

Database after failing:
![2](https://cloud.githubusercontent.com/assets/2769383/16676976/ba9e3b30-4513-11e6-9278-6c91113c4929.png)

So looks like its failing to create any boundary files.

_"--admin-bdys-path = This path should contain a subfolder named Administrative Boundaries."_
I fed in the argument for this to point to D:\DemoFolder\G-NAF\Downloads, which has a sub folder called Administrative Boundaries, which then has the various subfolders for each type, and these then have subfolders for Authority Code and Standard, as downloaded from data.gov.au.

I am a complete noob with PostGIS and also Python, but im guessing I have made a basic rookie error somewhere.  I know I can use the dump files you provide, but would like to get this working so I can get a better understanding of how it all works.  Care to put me out of my misery?

**Comment by keithamoss** [comment]
I can't reproduce this exactly, but gut feeling says it may relate to the hard-coding of the PG connection details.

What happens if you re-run pass them in [via the available parameters](https://github.com/minus34/gnaf-loader#postgres-parameters)? e.g.

```
python load-gnaf.py --gnaf-tables-path="D:\DemoFolder\G-NAF\Downloads\MAY16_GNAF_PipeSeparatedValue_20160523140820\G-NAF\G-NAF MAY 2016" --admin-bdys-path="D:\DemoFolder\G-NAF\Downloads" --states TAS ACT --pgdb="DATABASE" --pguser="USER" --pgpassword="PASSWORD"
```

**Comment by temasso** [comment]
Make sure you have PostgreSQL bin directory in your PATH. For test type shp2pgsql or psql in command line  (these bins are used in part 2).

**Comment by jakc** [comment]
Thanks for responding, just gotten around to looking at this again.

> Make sure you have PostgreSQL bin directory in your PATH.
I was missing this.  Have updated and can run both shp2pgsql & psql from a CMD.  However, script still fails with similar errors.

Bingo! Seems to have completed for VIC.  Let me try for all States and ill report back after the weekend...

**Comment by jakc** [comment]
Monday morning and looks like the script has completed successfully.  Here is the output from the CMD prompt - [pastebin](http://pastebin.com/RC7bc35P)

Unless you can spot something that looks out of place, I believe this issue can be closed off.  

![1](https://cloud.githubusercontent.com/assets/2769383/16903866/5e6ef324-4ccd-11e6-863f-566b85f8a40b.png)

**Comment by minus34** [comment]
Looks good! Have added a note to the readme to add the Postgres bin folder to system path as part of your setup.

Keith - please log the Wards issue for follow up.  Not sure I'll get to it before GovHack though!

**Comment by jakc** [comment]
Thanks all.  BTW, @keithamoss im working on incorporating this script (thanks @minus34) into a bigger automated workflow where I can create an Esri Address Locator from the data for the purpose of serving up to ArcGIS Server so you can register it with your portal.  Once I have sussed out the address locator styles, ill let you know if you want a copy.

**Comment by minus34** [comment]
No probs! Good stuff with the Locator work!
