### ISSUE TITLE
Missing documentation for changed option

### ISSUE THREAD

**Issue by migurski** [minus34/gnaf-loader#25]
We’ve [been using the `--no-boundary-tag` option in OpenAddresses](https://github.com/openaddresses/openaddresses/blob/0019d0d928e69d7b5cc8e5db46198691f8c8014e/scripts/au/gnaf.sh) which looks like it was recently removed. Can it be documented in the changelog?

**Comment by minus34** [comment]
Thanks, fixed in PR #26
