### ISSUE TITLE
Docker  Install Errors "raw_admin_bdys_201708.*** does not exist

### ISSUE THREAD

**Issue by deathsdealer** [minus34/gnaf-loader#28]
Hi,
Trying to install this on docker but getting lots of errors saying things don't exist.
Scripts gets here and stops.
[32mloader_1  |[0m Traceback (most recent call last):
[32mloader_1  |[0m   File "load-gnaf.py", line 940, in <module>
[32mloader_1  |[0m     if main():
[32mloader_1  |[0m   File "load-gnaf.py", line 98, in main
[32mloader_1  |[0m     create_reference_tables(pg_cur, settings)
[32mloader_1  |[0m   File "load-gnaf.py", line 636, in create_reference_tables
[32mloader_1  |[0m     pg_cur.execute(psma.open_sql_file("03-10-reference-split-melbourne.sql", settings))
[32mloader_1  |[0m psycopg2.ProgrammingError: relation "admin_bdys_201708.locality_bdys" does not exist
[32mloader_1  |[0m LINE 14:   FROM admin_bdys_201708.locality_bdys AS bdy
[32mloader_1  |[0m                 ^
[32mloader_1  |[0m 
[32mdata_loader_1 exited with code 1

**Comment by minus34** [comment]
Hi,

I can see in the log that the raw GNAF files and Admin boundary Shapefile couldn't be found. Check you've got the right input directories in your arguments and also check the file privileges so can be read.

10/30/2017 10:28:47 AM No raw GNAF PSV files found
ACTION: Check your 'gnaf-network-directory' path
...
10/30/2017 10:28:47 AM No admin boundary files found
ACTION: Check your 'admin-bdys-path' argument

**Comment by deathsdealer** [comment]
Do I need to edit the script to point to the directories? I have already given all the scripts chmod +x.

**Comment by minus34** [comment]
You'll need to set them as command line parameters as per this section of the readme:

https://github.com/minus34/gnaf-loader#required-arguments

There are some examples here: 

https://github.com/minus34/gnaf-loader#required-arguments

**Comment by deathsdealer** [comment]
I have set it to
python load-gnaf.py --gnaf-tables-path="/root/GNAF" --admin-bdys-path="/root/Administrative_Boundaries" --pghost db --pgdb gnaf --pguser gnaf --pgpassword gnaf

still getting same errors

**Comment by andrewharvey** [comment]
@deathsdealer I was going to suggest looking at how it's invoked at https://github.com/openaddresses/openaddresses/blob/master/scripts/au/gnaf.sh#L32 but it looks the same.

**Comment by flicj191** [comment]
I am getting similar issues though using windows.
`root        : CRITICAL No raw GNAF PSV files found
ACTION: Check your 'gnaf_network_directory' path`

this is the command
`PS C:\gnaf\gnaf-loader-master> python load-gnaf.py --gnaf-tables-path="C:\gnaf\GNAF_FEB_2018" --admin-bdys-p
ath="C:\gnaf\FEB28_AdminBounds_ESRI" --pgport 5433 --pgdb psma_201802 --pgpassword password
root        : INFO
root        : INFO     Start gnaf-loader
root        : INFO      - running Python 2.7.14 with Psycopg2 2.7.4
root        : INFO      - on Windows 10.0.16299
root        : INFO      - using Postgres 9.5.12 and PostGIS 2.3.5 (with GEOS 3.6.2-CAPI-1.10.2)
root        : INFO`

I have check directory access where ever I could and moved them to different locations. Is there something else I am missing?

**Comment by minus34** [comment]
The original issue has been resolved (a while back) through better logging of Shapefile loading. Errors now indicate whether there's a source file problem.
