### ISSUE TITLE
Geocode Level

### ISSUE THREAD

**Issue by CMCDragonkai** [minus34/gnaf-loader#31]
Is there a way to get the `LEVEL_GEOCODED_CODE`? I noticed that alot of stuff has been changed to create the tables in PostGIS. The summary at the bottom of the README isn't really comprehensive. It's hard to relate the fields/tables mentioned in the product description with the final database you have created.

Also since I'm using your dump, I don't even have access to the original raw gnaf data.

**Comment by CMCDragonkai** [comment]
Does the final database contain multiple geocodes? Or some way of acquiring the geocode priority for multiple geocodes to the same address site? The product description mentions that addresses can have multiple geocodes. But the address tables only have rows corresponding to a single geocode?

**Comment by minus34** [comment]
The `level_geocoded_code` field isn't in the end result as it's not a very useful metric. It doesn't tell you how good a geocode on an address is. That data is in the `reliability` and `geocode_type` fields which are in the address tables.

You can derive `level_geocoded_code` via the existence of null or non-null values in the `street_locality_pid` and `locality_pid` fields for each address; as well as the fields I mentioned above.

It's one geocode per address. The code assigns the default geocode to each address; which is prioritised by the PSMA as something like this: 1. building centre > 2. street centre offset > 3. property centre > 4. the driveway > 5. some obscure geocode types > 6. street centre > 7. locality centre

**Comment by CMCDragonkai** [comment]
Thanks this means if an address had multiple geocodes attached to it in the raw GNAF data, you filtered it to only the "default" geocode. Which has a priority order I can see in the `GEOCODE_RELIABILITY_AUT` table. However when it says that the "sufficient to place geocode within address site boundary", I'm wondering what is the definition of the address site boundary?

It appears that it has something to do with the cadastral parcel?

**Comment by minus34** [comment]
Yes, a reliability 2 will always be within the cadastral boundary of the
property, whereas a 3 might not be.

**Comment by CMCDragonkai** [comment]
Thanks:

```sql
SELECT 
  count(CASE WHEN reliability <= 2 THEN 1 END) AS cadastralin, 
  count(CASE WHEN reliability > 2 THEN 1 END) AS cadastralout, 
  count(1) AS total 
FROM gnaf_201708.address_principals;
```

```
 cadastralin | cadastralout |   total    
-------------|--------------|------------
  12,981,057 |      667,078 | 13,648,135
```
