### ISSUE TITLE
docker-compose up failed dependencies

### ISSUE THREAD

**Issue by sean-finocchiaro** [minus34/gnaf-loader#34]
Attempting to run the docker image and getting this issue:

Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgis : Depends: libgdal1h (>= 1.9.0) but it is not installable
           Depends: libgeos-c1 (>= 3.4.2) but it is not installable
           Depends: liblwgeom-2.4-0 (>= 2.0.0) but it is not going to be installed
 postgresql-client-9.6 : Depends: libpq5 (>= 9.6.9) but 9.6.7-0+deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'loader' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends   postgresql-client-9.6 postgis &&   apt-get autoremove -y --purge &&   apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

**Comment by hampsterx** [comment]
```
FROM python:3.6-jessie
```

seems "python:3.6" is using stretch but the lines below are for jessie.

**Comment by akapei** [comment]
@hampsterx Thanks! That worked for me.

**Comment by hughcameron** [comment]
@hampsterx - your comment helped me out as well - thanks!

So https://github.com/minus34/gnaf-loader/blob/master/Dockerfile#L1 should read `FROM python:3.6-jessie` instead of `FROM python:3.6`

**Comment by minus34** [comment]
Issue fixed in latest commit
