### ISSUE TITLE
script fails with function st_subdivide(geometry, integer) does not exist

### ISSUE THREAD

**Issue by alexgleith** [minus34/gnaf-loader#4]
Log below.

Sorry I don't have the brainpower to troubleshoot it currently. I'll see if I can make a PR to fix it later on the weekend.

Using these admin boundaries: https://data.gov.au/dataset/psma-administrative-boundaries/resource/53c24b8e-4f55-4eed-a189-2fc0dcca6381

And this G-NAF: https://data.gov.au/dataset/geocoded-national-address-file-g-naf

```
Part 1 of 3 : Start raw GNAF load : 2016-02-27 09:03:28.022014
	- Step 1 of 6 : tables dropped : 0:00:00.120549
	- Step 2 of 6 : database NOT vacuumed
	- Step 3 of 6 : tables created : 0:00:00.073267
	- Step 4 of 6 : tables populated : 0:00:03.921974
	- Step 5 of 6 : indexes created: 0:00:08.050198
	- Step 6 of 6 : primary & foreign keys NOT created
Part 1 of 4 : Raw GNAF loaded! : 0:00:12.166740

Part 2 of 4 : Start raw admin boundary load : 2016-02-27 09:03:40.188783
	- Step 1 of 2 : raw admin boundaries loaded : 0:00:06.340119
Traceback (most recent call last):
  File "load-gnaf.py", line 628, in <module>
    main()
  File "load-gnaf.py", line 149, in main
    create_admin_bdys_for_analysis(pg_cur)
  File "load-gnaf.py", line 382, in create_admin_bdys_for_analysis
    pg_cur.execute(open_sql_file("02-02-create-admin-bdys-tables.sql"))
psycopg2.ProgrammingError: function st_subdivide(geometry, integer) does not exist
LINE 225:        ST_Subdivide((ST_Dump(ST_Buffer(geom, 0.0))).geom, 51...
```

**Comment by minus34** [comment]
You'll need to upgrade to Postgis 2.2, it's a new function!

**Comment by iaghugh** [comment]
Alternative is to disable the create analysis tables sections in the '02-02' postgres-scripts file.

FYI - ST_Subdivide is great for speeding up spatial queries on the data.

**Comment by alexgleith** [comment]
Oh, right. Fair enough. Now to work out how to upgrade the bloody thing without losing all my current data!

**Comment by minus34** [comment]
I'm going to put a flag in to bypass the problem since 2.2 is relatively
new.

Should have it done in 1-2 hours

**Comment by minus34** [comment]
Code now skips creation of analysis files using ST_Subdivide if PostGIS version less than 2.2.

NOTE: sql tables have also been renumbered - so grab the entire ZIP file of code again.
