### ISSUE TITLE
Top level Administrative Boundaries subfolder no longer exists

### ISSUE THREAD

**Issue by tonytheodore** [minus34/gnaf-loader#54]
The latest zipfile no longer has a single top level "Administrative Boundaries" subfolder - there are now state subfolders, each with their own "Administrative Boundaries".

Pointing to the folder containing `AdminBounds_MMMYY_STATE_GDA2020_SHP` folders seems to be working.

**Comment by minus34** [comment]
This has been fixed in the pull request an hour or so ago. Pull the latest cut of the repo and it'll work with the new admin bdys folder structure.

**Comment by tonytheodore** [comment]
Thanks. It was working with 69e731f, probably just needs a doc update.

**Comment by minus34** [comment]
Added a note to the changelog
