### ISSUE TITLE
'--states' command line argument doesn't take more than one state

### ISSUE THREAD

**Issue by minus34** [minus34/gnaf-loader#6]
I haven't been able to get the '--states' argument to work with more than one state.

e,g. --states=ACT NT  fails with invalid argument 'NT', even though [a StackExchange article](http://stackoverflow.com/questions/15753701/argparse-option-for-passing-a-list-as-option) indicates this is the correct syntax.

This is on a Windows 10 machine with Python 2.7.11

NOTE: the default (i.e. not using the --states flag) works fine and loads all states as expected.

**Comment by nyalldawson** [comment]
I think it should be `--states ACT NT` (ie, no '='). Let me test and confirm, and I'll send through a doc update

**Comment by minus34** [comment]
Thanks,I gave it a quick run and that's the correct syntax.  I'm happy to update the readme.

BKAC error. Closing.
