### ISSUE TITLE
union all over union

### ISSUE THREAD

**Issue by tjmcewan** [minus34/gnaf-loader#66]
The `addresses` views in the GNAF files use a `UNION` which seems to cause Postgres to check for duplicates before displaying data.  As the addresses are unique anyway, could you pretty please change the definition to `UNION ALL` so the data is displayed immediately? 🙏 

Totally understand if there's a reason not to.

Thanks again for this wonderful service!

**Comment by minus34** [comment]
Good call. fixed in commit #[46c9b5a](https://github.com/minus34/gnaf-loader/commit/46c9b5a437472572910084b4836fc1cd5efee719)
