### ISSUE TITLE
Latest Docker Image only Available for Mac (linux/arm64/v8)

### ISSUE THREAD

**Issue by ilfrich** [minus34/gnaf-loader#75]
Hi @minus34,

I just wanted to pull the latest Docker image (Feb23) and noticed that you must have upgraded your build machine to a new Mac. The image now is only available for the architecture `linux/arm64/v8`, which I cannot run on my Linux machine (`linux/amd64`).

Is it possible that you can build and push for multiple platforms? Afaik, this is possible by using `docker build --platform linux/amd64 <...>` in the build process (or could require `docker buildx build ...` command - I'm not a docker expert).

For now, the old version from Nov22 is still recent enough (and runs on `linux/amd64`), but eventually this would cause issues.

Here's a log of what pops out when I try to run this on my Fedora 33:
```
docker run --publish=5433:5432 minus34/gnafloader:latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by minus34** [comment]
That's for picking that up. This was the first build on my M2 MacBook. The --platform flag above is the correct override to use.

The latest & 202302 containers have been fixed. GDA2020 containers are stil being uploaded and will be availabe in the couple of hours.

**Comment by ilfrich** [comment]
Thanks Hugh!
