### ISSUE TITLE
README inconsistency with May 2023 GNAF

### ISSUE THREAD

**Issue by pdowling-udrew** [minus34/gnaf-loader#79]
The README notes:
"--admin-bdys-path specifies the path to the extracted source admin boundary files. This path should contain a subfolder named Administrative Boundaries."
This subfolder doesn't exist in the ABS downloads (any more?) The November 2022 boundaries had a folder called NOV22_AdminBounds_GDA2020_SHP with everything under that, the May 2023 boundary folders are top-level folders within the zip.

I think this lead me down a bit of a rabbithole, I created a folder called "Administrative Boundaries" under my target folder, extracted the May 2023 ABS zip under that, and the script failed to find any of the admin boundary data at all. Extracting the ABS zip directly into my target folder works.

**Comment by minus34** [comment]
Thanks for picking that up. That information is out of date and obviously misleading. I've removed the sentence from the README.

You only need to reference the directory of the unzipped admin boundaries.
