### ISSUE TITLE
[Q] source of dump files

### ISSUE THREAD

**Issue by SpareShade** [minus34/gnaf-loader#85]
Hey @minus34, thank you for this great utility!!

What is the source of the pg_dump files from https://github.com/minus34/gnaf-loader#option-3---load-pg_dump-files?

The reason I'm asking is that I was looking for them on geoscape/data.gov.au websites but could not find them... the only place to have them is here :)

Also, there a number of tables missing, eg. `address_aliases`, `localities`, etc. that error during pg_restore, eg.
```js
pg_restore: error: could not execute query: ERROR:  relation "gnaf_202405.address_aliases" does not exist
Command was: ALTER TABLE gnaf_202405.address_aliases OWNER TO postgres;
```

Thanks again!

**Comment by minus34** [comment]
Thanks @SpareShade!

The dump files are the full GNAF and Admin Bdy schemas created by _gnaf-loader_, not the raw schemas provided by Geoscape. They're not official versions as I've done a fair amount of optimisation and cleanup to make the datasets easier to use; and so you won't find them on geoscape.com.au or data.gov.au.

As for the error you're getting. That's very odd. I loaded the dump files on my work MacBook and that table is there along with the rest.

Are you running Postgres 14 or above?

**Comment by ivanb777** [comment]
Thanks for the clarification @minus34!

The `error` is on me, being too eager I've skipped the PostGIS installation... but dumps restore without errors.

Thanks again for sharing this 🎆 !
